FROM debian:stretch
MAINTAINER Epiconcept

ENV USER=$USER
ENV LANG=C
ENV TZ=Europe/Paris
RUN $ADDUSER
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\nalias l='ls -Al'\ntest -f /opt/share/cfg && . /opt/share/cfg" >>/root/.bashrc

# Update/upgrade, install tools
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends vim file net-tools curl gnupg

CMD [ "/bin/bash" ]
