#!/bin/sh
#
#	apt - Interface to remote APT repository admin
#
Prg=$(basename "$0")
Usr='epiconcept_build'
Srv='51.255.164.1'
Top='/space/www/apps'
test "$Prg" = 'apt' && Apt="$Top/apt" || Apt="$Top/$Prg/site"

Ssh()
{
    #global Usr Srv
    ssh $Usr@$Srv "$@"
}

test "$1" = 'prep' -o "$1" = 'prod' || { echo "Usage: $Prg prep | prod <arguments>" >&2; exit 1; }
Cmd="$1"
shift

Ssh "$Apt/$Cmd.sh" "$@"
