#!/bin/sh
#
#	ubudeb - Show debian_version of ubuntu version passed as arg
#
test "$1" || { echo "Usage: $0 <Ubuntu-version>" >&2; exit 1; }
docker run -ti --name epi-ubu --rm ubuntu:$1 cat /etc/debian_version
